---
# tasks file for test_web

    - name: git repo
      git:
        repo: 'https://github.com/komarserjio/notejam.git'     
        dest: ./django
          
    - name: pip install requirements
      pip:
        requirements: "{{ lookup('env', 'PWD') }}/django/django/requirements.txt"        

    - name: assign ENGINE
      lineinfile: 
        path: "{{ lookup('env', 'PWD') }}/django/django/notejam/notejam/settings.py"
        regexp: 'ENGINE'
        line: "'ENGINE': 'django.db.backends.mysql',"  

    - name: assign NAME
      lineinfile:
        path: "{{ lookup('env', 'PWD') }}/django/django/notejam/notejam/settings.py"
        regexp: 'NAME'
        line: "'NAME': 'django_db',"

    - name: assign USER
      lineinfile:
        path: "{{ lookup('env', 'PWD') }}/django/django/notejam/notejam/settings.py"
        regexp: 'USER'
        line: "'USER': 'db_user',"

    - name: assign PASSWORD
      lineinfile:
        path: "{{ lookup('env', 'PWD') }}/django/django/notejam/notejam/settings.py"
        regexp: 'PASSWORD'
        line: "'PASSWORD': 'Passw0rd',"

    - name: assign HOST
      lineinfile:
        path: "{{ lookup('env', 'PWD') }}/django/django/notejam/notejam/settings.py"
        regexp: 'HOST'
        line: "'HOST': 'localhost',"

    - name: assign PORT
      lineinfile:
        path: "{{ lookup('env', 'PWD') }}/django/django/notejam/notejam/settings.py"
        regexp: 'PORT'
        line: "'PORT': '3306',"

    
    - name: execute syncdb
      script: "{{ lookup('env', 'PWD') }}/django/django/notejam/manage.py syncdb --noinput"
      args:
        executable: python

    - name: execute migrate
      script: "{{ lookup('env', 'PWD') }}/django/django/notejam/manage.py migrate"
      args:
        executable: python


    - name: Create file django_web.service file
      copy:
        dest: "/usr/local/bin/django_web.service"
        content: |
          [Service]
          ExecStart="{{ lookup('env', 'PWD') }}/django/django/notejam/manage.py runserver"
          
    - name: Start running the server
      systemd:
        name: django_web.service
        state: started
        

