---
# tasks file for test_web

    - name: git repo
      git:
        repo: 'https://github.com/komarserjio/notejam.git'     
        dest: ./django
          
#    - name: pip install virtualenv
#      pip:
#        name: pip
#        state: latest
         
    - name: pip install virtualenv
      pip:
        name: virtualenv

    - name: create virtual environment django_env
      shell:
        cmd: virtualenv django_env

    - name: activate django_env virtual environment
      shell: "source {{ lookup('env', 'PWD') }}/django_env/bin/activate"
      args:
        executable: /bin/bash   
          
    - name: pip install requirements
      pip:
        requirements: "{{ lookup('env', 'PWD') }}/django/django/requirements.txt"  
        virtualenv: "{{ lookup('env', 'PWD') }}/django_env"

    - name: pip install mysql-python
      pip:
        name: mysql-python
        virtualenv: "{{ lookup('env', 'PWD') }}/django_env"

    - name: assign ENGINE
      lineinfile: 
        path: "{{ lookup('env', 'PWD') }}/django/django/notejam/notejam/settings.py"
        regexp: 'ENGINE'
        line: "'ENGINE': 'django.db.backends.mysql',"  

    - name: assign NAME
      lineinfile:
        path: "{{ lookup('env', 'PWD') }}/django/django/notejam/notejam/settings.py"
        regexp: 'NAME'
        line: "'NAME': 'django_db',"

    - name: assign USER
      lineinfile:
        path: "{{ lookup('env', 'PWD') }}/django/django/notejam/notejam/settings.py"
        regexp: 'USER'
        line: "'USER': 'db_user',"

    - name: assign PASSWORD
      lineinfile:
        path: "{{ lookup('env', 'PWD') }}/django/django/notejam/notejam/settings.py"
        regexp: 'PASSWORD'
        line: "'PASSWORD': 'Passw0rd',"

    - name: assign HOST
      lineinfile:
        path: "{{ lookup('env', 'PWD') }}/django/django/notejam/notejam/settings.py"
        regexp: 'HOST'
        line: "'HOST': 'localhost',"

    - name: assign PORT
      lineinfile:
        path: "{{ lookup('env', 'PWD') }}/django/django/notejam/notejam/settings.py"
        regexp: 'PORT'
        line: "'PORT': '3306',"

    
    - name: execute syncdb
      script: "{{ lookup('env', 'PWD') }}/django/django/notejam/manage.py syncdb --noinput"
      args:
        executable: python

    - name: execute migrate
      script: "{{ lookup('env', 'PWD') }}/django/django/notejam/manage.py migrate"
      args:
        executable: python


    - name: Create file django_web.service file
      copy:
        dest: "/etc/systemd/system/django_web.service"
        content: |
          After=network.service
          [Service]
          ExecStart="{{ lookup('env', 'PWD')}}/django_env/bin/python  {{ lookup('env', 'PWD') }}/django/django/notejam/manage.py runserver"
          
    - name: Start running the server
      systemd:
        name: django_web.service
        state: started
        

