---
# tasks file for test_web

    - name: git repo
      git:
        repo: 'https://github.com/komarserjio/notejam.git'     
        dest: ./django
      become: yes  
          
    - name: pip install virtualenv
      pip:
        name: virtualenv
      become: yes  
        
    - name: create virtual environment django_env
      shell: "virtualenv django_env"
      args:
        executable: /bin/bash      

    - name: activate django_env virtual environment
      shell: "source {{ lookup('env', 'PWD') }}/django_env/bin/activate"
      args:
        executable: /bin/bash   
          
    - name: pip install requirements
      pip:
        requirements: "{{ lookup('env', 'PWD') }}/django/django/requirements.txt"  
        virtualenv: "{{ lookup('env', 'PWD') }}/django_env"

    - name: pip install mysql-python
      pip:
        name: mysql-python
        virtualenv: "{{ lookup('env', 'PWD') }}/django_env"

    - name: assign ENGINE
      lineinfile: 
        path: "{{ lookup('env', 'PWD') }}/django/django/notejam/notejam/settings.py"
        regexp: 'ENGINE'
        line: "'ENGINE': 'django.db.backends.mysql'," 
      become: yes  

    - name: assign NAME
      lineinfile:
        path: "{{ lookup('env', 'PWD') }}/django/django/notejam/notejam/settings.py"
        regexp: 'NAME'
        line: "'NAME': 'django_db',"
      become: yes  

    - name: assign USER
      lineinfile:
        path: "{{ lookup('env', 'PWD') }}/django/django/notejam/notejam/settings.py"
        regexp: 'USER'
        line: "'USER': 'db_user',"
      become: yes  

    - name: assign PASSWORD
      lineinfile:
        path: "{{ lookup('env', 'PWD') }}/django/django/notejam/notejam/settings.py"
        regexp: 'PASSWORD'
        line: "'PASSWORD': 'Passw0rd',"
      become: yes  

    - name: assign HOST
      lineinfile:
        path: "{{ lookup('env', 'PWD') }}/django/django/notejam/notejam/settings.py"
        regexp: 'HOST'
        line: "'HOST': 'localhost',"
      become: yes  

    - name: assign PORT
      lineinfile:
        path: "{{ lookup('env', 'PWD') }}/django/django/notejam/notejam/settings.py"
        regexp: 'PORT'
        line: "'PORT': '3306',"
      become: yes  

    
    - name: execute syncdb
      script: "{{ lookup('env', 'PWD') }}/django/django/notejam/manage.py syncdb --noinput"
      args:
        executable: "{{ lookup('env', 'PWD') }}/django_env/bin/python2.7"

    - name: execute migrate
      script: "{{ lookup('env', 'PWD') }}/django/django/notejam/manage.py migrate"
      args:
        executable: "{{ lookup('env', 'PWD') }}/django_env/bin/python2.7"


    - name: Create django_web.service file
      copy:
        dest: "/etc/systemd/system/django_web.service"
        content: |
          After=network.service
          [Service]
          ExecStart="{{ lookup('env', 'PWD')}}/django_env/bin/python  {{ lookup('env', 'PWD') }}/django/django/notejam/manage.py runserver"
      become: yes 
    
    - name: Start running the server
      systemd:
        name: django_web.service
        state: started
      become: yes  
        

